services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning